using Go;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ScenarioCollection
{
    public partial class ScenarioHelper
    {

        private static void AddXuanXuanGoSet_Release(List<Func<Scenario, Game>> scenarioList)
        {
            scenarioList.Add(x => x.Scenario_XuanXuanQiJing_A1());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_A2());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_A3());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_A4());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_A6());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_A7());
            scenarioList.Add(x => x.Scenario_XuanXuanQiJing_A8());
            scenarioList.Add(x => x.Scenario_XuanXuanQiJing_A11());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_A14());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_A17());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_A20());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_A23());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_A26());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_A27());
            scenarioList.Add(x => x.Scenario_XuanXuanQiJing_A33());
            scenarioList.Add(x => x.Scenario_XuanXuanQiJing_Weiqi101_A19());
            scenarioList.Add(x => x.Scenario_XuanXuanQiJing_Weiqi101_B4());
            scenarioList.Add(x => x.Scenario_XuanXuanQiJing_Weiqi101_2282());
            scenarioList.Add(x => x.Scenario_XuanXuanQiJing_Weiqi101_2398());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_Q6710());
            scenarioList.Add(x => x.Scenario_XuanXuanQiJing_Weiqi101_B19());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_A34());
            scenarioList.Add(x => x.Scenario_XuanXuanQiJing_A36());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_A115_101Weiqi());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_A75_101Weiqi());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_A37_101Weiqi());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_Q18341());
            scenarioList.Add(x => x.Scenario_XuanXuanQiJing_A46());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_Q18474());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_A49());
            scenarioList.Add(x => x.Scenario3dan16());
            scenarioList.Add(x => x.Scenario_XuanXuanQiJing_A52());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_B9());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_B10());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_B12());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_Q18331());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_Q18358());
            scenarioList.Add(x => x.Scenario_XuanXuanQiJing_A53());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_A57());
            scenarioList.Add(x => x.Scenario_XuanXuanQiJing_A61());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_A59());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_A66());
            scenarioList.Add(x => x.Scenario_XuanXuanQiJing_Weiqi101_7245());
            scenarioList.Add(x => x.Scenario_XuanXuanQiJing_B17());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_18467_101Weiqi());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_B6());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_B7());
            scenarioList.Add(x => x.Scenario_XuanXuanQiJing_Weiqi101_18402());
            scenarioList.Add(x => x.Scenario_XuanXuanQiJing_Weiqi101_18410());
            scenarioList.Add(x => x.Scenario_XuanXuanQiJing_Weiqi101_1887());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_B31());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_B32());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_B33());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_B35());
            scenarioList.Add(x => x.Scenario_XuanXuanQiJing_A64());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_A82_101Weiqi());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_A67_101Weiqi());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_A136_101Weiqi());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_A138_101Weiqi());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_A53_101Weiqi());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_A28_101Weiqi());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_A42());
            scenarioList.Add(x => x.Scenario_XuanXuanQiJing_Weiqi101_18497());
            scenarioList.Add(x => x.Scenario_XuanXuanQiJing_Weiqi101_B51());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_A171_101Weiqi());
            scenarioList.Add(x => x.Scenario_XuanXuanQiJing_B57());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_B3());
            scenarioList.Add(x => x.Scenario_XuanXuanQiJing_A39());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_A41());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_Q18500());
            scenarioList.Add(x => x.Scenario_XuanXuanQiJing_Weiqi101_B74());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_A151_101Weiqi());

        }


        private static void AddGuanZiPuSet_Release(List<Func<Scenario, Game>> scenarioList)
        {
            scenarioList.Add(x => x.Scenario_GuanZiPu_Q14967());
            scenarioList.Add(x => x.Scenario_GuanZiPu_Q19020());
            scenarioList.Add(x => x.Scenario_GuanZiPu_Q19336());
            scenarioList.Add(x => x.Scenario_GuanZiPu_A2());
            scenarioList.Add(x => x.Scenario_GuanZiPu_A3());
            scenarioList.Add(x => x.Scenario_GuanZiPu_A4());
            scenarioList.Add(x => x.Scenario_GuanZiPu_A6());
            scenarioList.Add(x => x.Scenario_GuanZiPu_A7());
            scenarioList.Add(x => x.Scenario_GuanZiPu_Q1970());
            scenarioList.Add(x => x.Scenario_GuanZiPu_A9());
            scenarioList.Add(x => x.Scenario_GuanZiPu_A12());
            scenarioList.Add(x => x.Scenario_GuanZiPu_A14());
            scenarioList.Add(x => x.Scenario_GuanZiPu_Q18710());
            scenarioList.Add(x => x.Scenario_GuanZiPu_Q19013());
            scenarioList.Add(x => x.Scenario_GuanZiPu_Q19012());
            scenarioList.Add(x => x.Scenario_GuanZiPu_Q18796());
            scenarioList.Add(x => x.Scenario_GuanZiPu_Q2622());
            scenarioList.Add(x => x.Scenario_GuanZiPu_Weiqi101_19138());
            scenarioList.Add(x => x.Scenario_GuanZiPu_A15());
            scenarioList.Add(x => x.Scenario_GuanZiPu_A16());
            scenarioList.Add(x => x.Scenario_GuanZiPu_A19());
            scenarioList.Add(x => x.Scenario_GuanZiPu_A20());
            scenarioList.Add(x => x.Scenario_GuanZiPu_A25());
            scenarioList.Add(x => x.Scenario_GuanZiPu_B1());
            scenarioList.Add(x => x.Scenario_GuanZiPu_B7());
            scenarioList.Add(x => x.Scenario_GuanZiPu_B15());
            scenarioList.Add(x => x.Scenario_GuanZiPu_B18());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_A145_101Weiqi());
            scenarioList.Add(x => x.Scenario_GuanZiPu_B3Q63_101Weiqi());
            scenarioList.Add(x => x.Scenario_GuanZiPu_A2Q71_101Weiqi());
            scenarioList.Add(x => x.Scenario_SiHuoDaQuan_CornerA117());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_A13_Ext());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_A15());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_A16());
            scenarioList.Add(x => x.Scenario_GuanZiPu_A2Q28_101Weiqi());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_A18());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_A28());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_A30());
            scenarioList.Add(x => x.Scenario_GuanZiPu_A32());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_Q18472());
            scenarioList.Add(x => x.Scenario_GuanZiPu_A30());
            scenarioList.Add(x => x.Scenario_GuanZiPu_A31());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_Q18340());
            scenarioList.Add(x => x.Scenario_GuanZiPu_A4Q11_101Weiqi());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_A48());
            scenarioList.Add(x => x.Scenario_XuanXuanQiJing_A40());
            scenarioList.Add(x => x.Scenario_XuanXuanQiJing_Weiqi101_A40());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_A55());
            scenarioList.Add(x => x.Scenario_GuanZiPu_Q14981());
            scenarioList.Add(x => x.Scenario_GuanZiPu_Q18860());
            scenarioList.Add(x => x.Scenario_GuanZiPu_Q14906());
            scenarioList.Add(x => x.Scenario_GuanZiPu_Q14971());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_A44_101Weiqi());
            scenarioList.Add(x => x.Scenario_GuanZiPu_A17());
            scenarioList.Add(x => x.Scenario_GuanZiPu_A18());
            scenarioList.Add(x => x.Scenario_GuanZiPu_A26());
            scenarioList.Add(x => x.Scenario_GuanZiPu_A29());
            scenarioList.Add(x => x.Scenario_GuanZiPu_A27());
            scenarioList.Add(x => x.Scenario_GuanZiPu_B3());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q16525());
            scenarioList.Add(x => x.Scenario_Nie137());
            scenarioList.Add(x => x.Scenario_XuanXuanQiJing_A38());
            scenarioList.Add(x => x.Scenario_XuanXuanQiJing_B36());
            scenarioList.Add(x => x.Scenario_XuanXuanQiJing_B25());
            scenarioList.Add(x => x.Scenario_GuanZiPu_A35());
            scenarioList.Add(x => x.Scenario_GuanZiPu_A36());
            scenarioList.Add(x => x.Scenario_GuanZiPu_A37());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_A54());
            scenarioList.Add(x => x.Scenario_XuanXuanGo_A67());
            scenarioList.Add(x => x.Scenario_GuanZiPu_A2Q29_101Weiqi());
            scenarioList.Add(x => x.ScenarioHighLevel28());
        }



        private static void AddWuQingYuanSet_Release(List<Func<Scenario, Game>> scenarioList)
        {
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q1783());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q5971());
            scenarioList.Add(x => x.Scenario_Corner_A126());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q6150());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q15126());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q16508());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q30919());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q30934());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q30935());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q30981());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q30982());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q30986());
            scenarioList.Add(x => x.Scenario_Corner_A130());
            scenarioList.Add(x => x.Scenario_Corner_A139());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31171());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31177());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31154());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31225());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31240());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31305());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31326());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31329());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31339());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31366());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31365());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q3849());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31398());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31419());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31428());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31430());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31435());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31444());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31445());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31449());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31450());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31453());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31466());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31469());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31471());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31493());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31498());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31499());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31503());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31510());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31514());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31525());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31526());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31530());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31533());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31536());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31537());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31542());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31563());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31564());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31575());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31580());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31585());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31587());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31602());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31603());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31640());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31646());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31657());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31670());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31673());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31680());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31682());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31686());
            scenarioList.Add(x => x.Scenario_WuQingYuan_Q31672());
            scenarioList.Add(x => x.Scenario_Corner_A137());
        }

        private static void AddWindAndTimeSet(List<Func<Scenario, Game>> scenarioList)
        {
            scenarioList.Add(x => x.Scenario_WindAndTime_Q2757());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q29264());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q29273());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q29277());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q29285());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q29290());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q29294());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q29345());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q29366());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q29208());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q29378());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q29410());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q29424());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q29445());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q29475());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q29478());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q29481());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q29487());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q29958());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q29961());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q29998());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q30005());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q30010());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q30034());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q30051());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q30053());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q30057());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q30064());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q30150());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q30152());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q30158());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q30188());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q30196());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q30198());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q30199());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q30201());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q30205());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q30213());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q30215());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q30221());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q30222());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q30224());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q30231());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q30234());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q30240());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q30241());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q30251());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q30254());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q30256());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q30260());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q30267());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q30269());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q30271());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q30274());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q30275());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q30278());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q30279());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q30302());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q30315());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q30322());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q30332());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q30348());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q30357());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q30358());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q30364());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q30370());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q30403());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q30406());
            scenarioList.Add(x => x.Scenario_WindAndTime_Q30225());

        }

        private static void AddTianLongTuSet_Release(List<Func<Scenario, Game>> scenarioList)
        {
            scenarioList.Add(x => x.Scenario_TianLongTu_Q15082());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q14916());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q16605());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q16574());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q16444());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q16470());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q16483());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q14992());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q16520());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q16487());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q15017());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q16446());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q16456());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q15054());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q16693());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q16490());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q16711());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q16867());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q16760());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q16748());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q16768());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q15618());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q16747());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q16851());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q16850());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q16859());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q16902());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q16936());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q16931());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q16924());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q16973());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q16975());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q17078());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q16754());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q16827());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q16872());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q16985());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q17077());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q17081());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q17154());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q17136());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q17241());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q17250());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q16604());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q17239());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q17255());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q2176());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q17183());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q17112());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q16925());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q16466());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q16571());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q16594());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q16735());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q2834());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q16738());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q27661());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q16424());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q16919());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q15301());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q16673());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q2174());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q2413());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q17143());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q17198());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q17160());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q16860());
            scenarioList.Add(x => x.Scenario_TianLongTu_Q17132());

        }


    }
}
