//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScenarioCollection.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GoSeigen_MappedJsonExtension {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GoSeigen_MappedJsonExtension() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScenarioCollection.Resources.GoSeigen_MappedJsonExtension", typeof(GoSeigen_MappedJsonExtension).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15},&quot;SecondMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:15},&quot;FourthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:13},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18}}]},{&quot;ThirdMove&quot;:{&quot;x&quot;:0,&....
        /// </summary>
        internal static string Scenario_WuQingYuan_Q1783_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WuQingYuan_Q1783_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:15},&quot;SecondMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:16},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&qu....
        /// </summary>
        internal static string Scenario_WuQingYuan_Q1783_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WuQingYuan_Q1783_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SecondMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:16},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:16},&quot;FourthMove&quot;:{&quot;x&quot;:9,&quot;y&quot;:17},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:9,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:9,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:9,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:9,&qu....
        /// </summary>
        internal static string Scenario_WuQingYuan_Q30919_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WuQingYuan_Q30919_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SecondMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17},&quot;FourthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:10,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:10,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:8,&....
        /// </summary>
        internal static string Scenario_WuQingYuan_Q30919_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WuQingYuan_Q30919_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:9,&quot;y&quot;:16},&quot;SecondMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:16},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:16},&quot;FourthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:17},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:9,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:8,&qu....
        /// </summary>
        internal static string Scenario_WuQingYuan_Q30934_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WuQingYuan_Q30934_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16},&quot;SecondMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16},&quot;FourthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:17},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&qu....
        /// </summary>
        internal static string Scenario_WuQingYuan_Q30935_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WuQingYuan_Q30935_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16},&quot;SecondMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:9,&quot;y&quot;:16},&quot;FourthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:17},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:10,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:9,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:10,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:11,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:10,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:10,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:10,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:10,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:10,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quo....
        /// </summary>
        internal static string Scenario_WuQingYuan_Q30982_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WuQingYuan_Q30982_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:16},&quot;SecondMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16},&quot;FourthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:9,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:9,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:9,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:10,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&q....
        /// </summary>
        internal static string Scenario_WuQingYuan_Q30986_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WuQingYuan_Q30986_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SecondMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:16},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:9,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&qu....
        /// </summary>
        internal static string Scenario_WuQingYuan_Q31103_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WuQingYuan_Q31103_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:14},&quot;SecondMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:15},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:14},&quot;FourthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:17},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:9,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:8,&qu....
        /// </summary>
        internal static string Scenario_WuQingYuan_Q31154_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WuQingYuan_Q31154_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16},&quot;SecondMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:15},&quot;FourthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;ThirdMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;ThirdMove&quot;:{&quot;x&quot;:10,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:15}},{&quot;ThirdMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:15}},{&quot;ThirdMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:15}},{&quot;ThirdMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&quot;FourthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:15}},{&quot;ThirdMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:15},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot....
        /// </summary>
        internal static string Scenario_WuQingYuan_Q31177_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WuQingYuan_Q31177_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16},&quot;SecondMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:15},&quot;FourthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18}},{&quot;ThirdMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18}},{&quot;ThirdMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&quot;FourthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18}},{&quot;ThirdMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18}},{&quot;ThirdMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18}},{&quot;ThirdMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18}},{&quot;ThirdMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;....
        /// </summary>
        internal static string Scenario_WuQingYuan_Q31177_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WuQingYuan_Q31177_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SecondMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:17},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:10,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&q....
        /// </summary>
        internal static string Scenario_WuQingYuan_Q31225_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WuQingYuan_Q31225_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SecondMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16},&quot;FourthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:9,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&qu....
        /// </summary>
        internal static string Scenario_WuQingYuan_Q31225_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WuQingYuan_Q31225_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SecondMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:17},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:9,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&qu....
        /// </summary>
        internal static string Scenario_WuQingYuan_Q31240_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WuQingYuan_Q31240_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SecondMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:10,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&q....
        /// </summary>
        internal static string Scenario_WuQingYuan_Q31240_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WuQingYuan_Q31240_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:14},&quot;SecondMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:15},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:14},&quot;FourthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:14},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&qu....
        /// </summary>
        internal static string Scenario_WuQingYuan_Q31305_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WuQingYuan_Q31305_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:16},&quot;SecondMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:14},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&qu....
        /// </summary>
        internal static string Scenario_WuQingYuan_Q31339_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WuQingYuan_Q31339_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:16},&quot;SecondMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:9,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:8,&qu....
        /// </summary>
        internal static string Scenario_WuQingYuan_Q31398_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WuQingYuan_Q31398_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17},&quot;SecondMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&quot;FourthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:10,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&q....
        /// </summary>
        internal static string Scenario_WuQingYuan_Q31398_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WuQingYuan_Q31398_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:15},&quot;SecondMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16},&quot;FourthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:8,&qu....
        /// </summary>
        internal static string Scenario_WuQingYuan_Q31444_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WuQingYuan_Q31444_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:17},&quot;SecondMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:16},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&qu....
        /// </summary>
        internal static string Scenario_WuQingYuan_Q31453_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WuQingYuan_Q31453_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16},&quot;SecondMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:15},&quot;FourthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:15},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:14}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:14}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:14},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:14}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&qu....
        /// </summary>
        internal static string Scenario_WuQingYuan_Q31493_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WuQingYuan_Q31493_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:15},&quot;SecondMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:14},&quot;FourthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&qu....
        /// </summary>
        internal static string Scenario_WuQingYuan_Q31493_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WuQingYuan_Q31493_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:16},&quot;SecondMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&qu....
        /// </summary>
        internal static string Scenario_WuQingYuan_Q31495_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WuQingYuan_Q31495_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15},&quot;SecondMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:16},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&qu....
        /// </summary>
        internal static string Scenario_WuQingYuan_Q31495_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WuQingYuan_Q31495_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16},&quot;SecondMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:16},&quot;FourthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:17},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&qu....
        /// </summary>
        internal static string Scenario_WuQingYuan_Q31498_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WuQingYuan_Q31498_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:14},&quot;SecondMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;FourthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:18},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&qu....
        /// </summary>
        internal static string Scenario_WuQingYuan_Q31499_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WuQingYuan_Q31499_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:14},&quot;SecondMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;FourthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:14}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:14},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&qu....
        /// </summary>
        internal static string Scenario_WuQingYuan_Q31499_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WuQingYuan_Q31499_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:15},&quot;SecondMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:16},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:8,&qu....
        /// </summary>
        internal static string Scenario_WuQingYuan_Q31510_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WuQingYuan_Q31510_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:15},&quot;SecondMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:16},&quot;FourthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&qu....
        /// </summary>
        internal static string Scenario_WuQingYuan_Q31536_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WuQingYuan_Q31536_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SecondMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:16},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:14}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:14},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&qu....
        /// </summary>
        internal static string Scenario_WuQingYuan_Q31537_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WuQingYuan_Q31537_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17},&quot;SecondMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&quot;FourthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&qu....
        /// </summary>
        internal static string Scenario_WuQingYuan_Q31580_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WuQingYuan_Q31580_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&quot;SecondMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&qu....
        /// </summary>
        internal static string Scenario_WuQingYuan_Q31580_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WuQingYuan_Q31580_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&quot;SecondMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17},&quot;FourthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:13},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:14},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:14}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:14}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:14}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&qu....
        /// </summary>
        internal static string Scenario_WuQingYuan_Q31585_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WuQingYuan_Q31585_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SecondMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17},&quot;FourthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:13},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:14}},{&quot;FifthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&qu....
        /// </summary>
        internal static string Scenario_WuQingYuan_Q31585_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WuQingYuan_Q31585_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:16},&quot;SecondMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16},&quot;FourthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:9,&qu....
        /// </summary>
        internal static string Scenario_WuQingYuan_Q31587_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WuQingYuan_Q31587_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SecondMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:17},&quot;FourthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:16},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&qu....
        /// </summary>
        internal static string Scenario_WuQingYuan_Q31602_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WuQingYuan_Q31602_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:16},&quot;SecondMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:9,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:17},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&qu....
        /// </summary>
        internal static string Scenario_WuQingYuan_Q31602_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WuQingYuan_Q31602_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:9,&quot;y&quot;:16},&quot;SecondMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:9,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:17},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&qu....
        /// </summary>
        internal static string Scenario_WuQingYuan_Q31672_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WuQingYuan_Q31672_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17},&quot;SecondMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:9,&quot;y&quot;:18},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:9,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:9,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:9,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:9,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:8,&qu....
        /// </summary>
        internal static string Scenario_WuQingYuan_Q31673_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WuQingYuan_Q31673_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:11,&quot;y&quot;:18},&quot;SecondMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:10,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:17},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:9,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:8,&....
        /// </summary>
        internal static string Scenario_WuQingYuan_Q31673_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WuQingYuan_Q31673_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:14},&quot;SecondMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:15},&quot;FourthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&qu....
        /// </summary>
        internal static string Scenario_WuQingYuan_Q31682_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WuQingYuan_Q31682_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SecondMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:15},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15},&quot;FourthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:14},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:14}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:14}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:14},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&qu....
        /// </summary>
        internal static string Scenario_WuQingYuan_Q3849_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WuQingYuan_Q3849_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:16},&quot;SecondMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:14},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:15},&quot;FourthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:14},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:14},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&qu....
        /// </summary>
        internal static string Scenario_WuQingYuan_Q6150_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WuQingYuan_Q6150_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:13},&quot;SecondMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:14},&quot;FourthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:17},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:14}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&qu....
        /// </summary>
        internal static string Scenario_WuQingYuan_Q6150_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WuQingYuan_Q6150_PlayerMoveExtension", resourceCulture);
            }
        }
    }
}
