//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScenarioCollection.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GuanZiPu_MappedJsonExtension {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GuanZiPu_MappedJsonExtension() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScenarioCollection.Resources.GuanZiPu_MappedJsonExtension", typeof(GuanZiPu_MappedJsonExtension).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17},&quot;SecondMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&qu....
        /// </summary>
        internal static string Scenario_GuanZiPu_A12_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_A12_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:17},&quot;SecondMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17},&quot;FourthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&qu....
        /// </summary>
        internal static string Scenario_GuanZiPu_A12_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_A12_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17},&quot;SecondMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:14}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&qu....
        /// </summary>
        internal static string Scenario_GuanZiPu_A14_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_A14_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16},&quot;SecondMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:17},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:14},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&qu....
        /// </summary>
        internal static string Scenario_GuanZiPu_A14_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_A14_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&quot;SecondMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:16},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17},&quot;FourthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&qu....
        /// </summary>
        internal static string Scenario_GuanZiPu_A17_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_A17_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16},&quot;SecondMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;FourthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&qu....
        /// </summary>
        internal static string Scenario_GuanZiPu_A17_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_A17_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:17},&quot;SecondMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:16},&quot;FourthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:14}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:14}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:14}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:14}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:14}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:14}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&qu....
        /// </summary>
        internal static string Scenario_GuanZiPu_A18_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_A18_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:14},&quot;SecondMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15},&quot;FourthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&qu....
        /// </summary>
        internal static string Scenario_GuanZiPu_A18_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_A18_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:15},&quot;SecondMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:16},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15},&quot;FourthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:16},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&qu....
        /// </summary>
        internal static string Scenario_GuanZiPu_A20_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_A20_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17},&quot;SecondMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:16},&quot;FourthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:16},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&qu....
        /// </summary>
        internal static string Scenario_GuanZiPu_A20_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_A20_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17},&quot;SecondMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:13},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:15},&quot;FourthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:17},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:12},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:13},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&qu....
        /// </summary>
        internal static string Scenario_GuanZiPu_A25_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_A25_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:12},&quot;SecondMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:13},&quot;FourthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:8,&qu....
        /// </summary>
        internal static string Scenario_GuanZiPu_A25_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_A25_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:16},&quot;SecondMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;FourthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:14},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&qu....
        /// </summary>
        internal static string Scenario_GuanZiPu_A2Q19_101Weiqi_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_A2Q19_101Weiqi_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16},&quot;SecondMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:13},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&qu....
        /// </summary>
        internal static string Scenario_GuanZiPu_A2Q19_101Weiqi_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_A2Q19_101Weiqi_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:13},&quot;SecondMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:18},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&qu....
        /// </summary>
        internal static string Scenario_GuanZiPu_A2Q28_101Weiqi_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_A2Q28_101Weiqi_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:15},&quot;SecondMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:15},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:17},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:14},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:14},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:14}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:13},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&qu....
        /// </summary>
        internal static string Scenario_GuanZiPu_A2Q28_101Weiqi_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_A2Q28_101Weiqi_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:17},&quot;SecondMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:17},&quot;FourthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&qu....
        /// </summary>
        internal static string Scenario_GuanZiPu_A2Q29_101Weiqi_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_A2Q29_101Weiqi_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:15},&quot;SecondMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15},&quot;FourthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:17},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&qu....
        /// </summary>
        internal static string Scenario_GuanZiPu_A2Q29_101Weiqi_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_A2Q29_101Weiqi_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16},&quot;SecondMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:9,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&qu....
        /// </summary>
        internal static string Scenario_GuanZiPu_A31_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_A31_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17},&quot;SecondMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&qu....
        /// </summary>
        internal static string Scenario_GuanZiPu_A35_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_A35_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:15},&quot;SecondMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:16},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&qu....
        /// </summary>
        internal static string Scenario_GuanZiPu_A35_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_A35_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18},&quot;SecondMove&quot;:{&quot;x&quot;:10,&quot;y&quot;:18},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:17},&quot;FourthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:11,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&....
        /// </summary>
        internal static string Scenario_GuanZiPu_A36_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_A36_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17},&quot;SecondMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:17},&quot;FourthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:9,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:10,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:9,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&q....
        /// </summary>
        internal static string Scenario_GuanZiPu_A36_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_A36_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17},&quot;SecondMove&quot;:{&quot;x&quot;:9,&quot;y&quot;:18},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:10,&quot;y&quot;:17},&quot;FourthMove&quot;:{&quot;x&quot;:10,&quot;y&quot;:18},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:11,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:11,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:11,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:11,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;....
        /// </summary>
        internal static string Scenario_GuanZiPu_A37_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_A37_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16},&quot;SecondMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:11,&quot;y&quot;:17},&quot;FourthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:17},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:10,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:9,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:11,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:12,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:9,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:10,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:....
        /// </summary>
        internal static string Scenario_GuanZiPu_A37_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_A37_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17},&quot;SecondMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:16},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:15},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&qu....
        /// </summary>
        internal static string Scenario_GuanZiPu_A4_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_A4_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:15},&quot;SecondMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:16},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;FourthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&qu....
        /// </summary>
        internal static string Scenario_GuanZiPu_A4_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_A4_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:15},&quot;SecondMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:17},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:14},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:14},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:13}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&qu....
        /// </summary>
        internal static string Scenario_GuanZiPu_A4Q11_101Weiqi_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_A4Q11_101Weiqi_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:14},&quot;SecondMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:14},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:15},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:13},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&qu....
        /// </summary>
        internal static string Scenario_GuanZiPu_A4Q11_101Weiqi_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_A4Q11_101Weiqi_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18},&quot;SecondMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&qu....
        /// </summary>
        internal static string Scenario_GuanZiPu_A9_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_A9_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:15},&quot;SecondMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:16},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15},&quot;FourthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&qu....
        /// </summary>
        internal static string Scenario_GuanZiPu_A9_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_A9_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18},&quot;SecondMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&quot;FourthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18}}]},{&quot;ThirdMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16},&quot;FourthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16}},{&quot;ThirdMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16},&quot;FourthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17}},{&quot;ThirdMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16},&quot;ThirdLevel&quot;:[{&quot;FifthMov....
        /// </summary>
        internal static string Scenario_GuanZiPu_B15_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_B15_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SecondMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16}}]},{&quot;ThirdMove&quot;:{&quot;x&quot;:5,&....
        /// </summary>
        internal static string Scenario_GuanZiPu_B15_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_B15_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SecondMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&quot;FourthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18}},{&quot;ThirdMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17}},{&quot;ThirdMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17}},{&quot;ThirdMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:17},&quot;FourthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17}},{&quot;ThirdMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17}},{&quot;ThirdMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:17},&quot;FourthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17}},{&quot;ThirdMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17}},{&quot;ThirdMove&quot;:{&quot;x&quot;:9,&quot;y&quot;:18},&q....
        /// </summary>
        internal static string Scenario_GuanZiPu_B18_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_B18_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&quot;SecondMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:9,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&qu....
        /// </summary>
        internal static string Scenario_GuanZiPu_B18_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_B18_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15},&quot;SecondMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:17},&quot;FourthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:14}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:14},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:14}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:13},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&qu....
        /// </summary>
        internal static string Scenario_GuanZiPu_B3_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_B3_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15},&quot;SecondMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16},&quot;FourthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:13},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&qu....
        /// </summary>
        internal static string Scenario_GuanZiPu_B3_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_B3_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:15},&quot;SecondMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:15},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:16},&quot;FourthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:14},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&qu....
        /// </summary>
        internal static string Scenario_GuanZiPu_B3Q63_101Weiqi_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_B3Q63_101Weiqi_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:14},&quot;SecondMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:14},&quot;FourthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&qu....
        /// </summary>
        internal static string Scenario_GuanZiPu_B3Q63_101Weiqi_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_B3Q63_101Weiqi_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:14},&quot;SecondMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16},&quot;FourthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:16},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&qu....
        /// </summary>
        internal static string Scenario_GuanZiPu_B4_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_B4_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:14},&quot;SecondMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&qu....
        /// </summary>
        internal static string Scenario_GuanZiPu_B4_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_B4_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:13},&quot;SecondMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:15},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:15},&quot;FourthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:14},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:13},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:14}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:13},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:14}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:13},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:14}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:13},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:14}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:14},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:14}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:14}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&qu....
        /// </summary>
        internal static string Scenario_GuanZiPu_B7_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_B7_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:14},&quot;SecondMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:15},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:14},&quot;FourthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:13},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:14},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:13},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:13}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:14}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:13}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:13},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:13}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:13},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:13}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&qu....
        /// </summary>
        internal static string Scenario_GuanZiPu_B7_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_B7_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15},&quot;SecondMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:14},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:17},&quot;FourthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:13},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&qu....
        /// </summary>
        internal static string Scenario_GuanZiPu_Q14906_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_Q14906_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:14},&quot;SecondMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:14},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&qu....
        /// </summary>
        internal static string Scenario_GuanZiPu_Q14906_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_Q14906_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:14},&quot;SecondMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:13},&quot;FourthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:14},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:14}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&qu....
        /// </summary>
        internal static string Scenario_GuanZiPu_Q14915_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_Q14915_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:15},&quot;SecondMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:15},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:17},&quot;FourthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&qu....
        /// </summary>
        internal static string Scenario_GuanZiPu_Q14971_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_Q14971_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SecondMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;FourthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:15},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&qu....
        /// </summary>
        internal static string Scenario_GuanZiPu_Q14971_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_Q14971_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:17},&quot;SecondMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:16},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:16},&quot;FourthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&qu....
        /// </summary>
        internal static string Scenario_GuanZiPu_Q14980_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_Q14980_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16},&quot;SecondMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:13},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&qu....
        /// </summary>
        internal static string Scenario_GuanZiPu_Q14980_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_Q14980_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15},&quot;SecondMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;FourthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&qu....
        /// </summary>
        internal static string Scenario_GuanZiPu_Q14981_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_Q14981_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:14},&quot;SecondMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:17},&quot;FourthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:16},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&qu....
        /// </summary>
        internal static string Scenario_GuanZiPu_Q15021_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_Q15021_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:18},&quot;SecondMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:16},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17},&quot;FourthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&qu....
        /// </summary>
        internal static string Scenario_GuanZiPu_Q18710_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_Q18710_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16},&quot;SecondMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:16},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:17},&quot;FourthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&qu....
        /// </summary>
        internal static string Scenario_GuanZiPu_Q18710_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_Q18710_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18},&quot;SecondMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17},&quot;FourthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:9,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:9,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:9,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:9,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:9,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:10,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:9,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&q....
        /// </summary>
        internal static string Scenario_GuanZiPu_Q19013_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_Q19013_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18},&quot;SecondMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:9,&quot;y&quot;:17},&quot;FourthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:10,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&q....
        /// </summary>
        internal static string Scenario_GuanZiPu_Q19013_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_Q19013_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:17},&quot;SecondMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18}},{&quot;ThirdMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18}},{&quot;ThirdMove&quot;:{&quot;x&quot;:9,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18}},{&quot;ThirdMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18}},{&quot;ThirdMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:16},&quot;FourthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18}},{&quot;ThirdMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18}},{&quot;ThirdMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:17},&quot;FourthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:16}},{&quot;ThirdMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&q....
        /// </summary>
        internal static string Scenario_GuanZiPu_Q19336_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_Q19336_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:16},&quot;SecondMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17}},{&quot;ThirdMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&quot;FourthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18}},{&quot;ThirdMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18}},{&quot;ThirdMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18}},{&quot;ThirdMove&quot;:{&quot;x&quot;:9,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18}},{&quot;ThirdMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:16},&quot;FourthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18}},{&quot;ThirdMove&quot;:{&quot;x&quot;:10,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18}},{&quot;ThirdMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&....
        /// </summary>
        internal static string Scenario_GuanZiPu_Q19336_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_Q19336_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:15},&quot;SecondMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:14},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:14},&quot;FourthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:14},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:13}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:13},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:13}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:13},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&qu....
        /// </summary>
        internal static string Scenario_GuanZiPu_Q1970_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_Q1970_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:13},&quot;SecondMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:14},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:14},&quot;FourthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:15},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:14},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:13},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:14}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:12},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:13},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:13}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:12},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:14}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:14}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&qu....
        /// </summary>
        internal static string Scenario_GuanZiPu_Q1970_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_Q1970_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:17},&quot;SecondMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:9,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:10,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:8,&q....
        /// </summary>
        internal static string Scenario_GuanZiPu_Weiqi101_19138_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_Weiqi101_19138_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:10,&quot;y&quot;:18},&quot;SecondMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:9,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&q....
        /// </summary>
        internal static string Scenario_GuanZiPu_Weiqi101_19138_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_GuanZiPu_Weiqi101_19138_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:17},&quot;SecondMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18}},{&quot;FirstMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SecondMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18}},{&quot;FirstMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17},&quot;SecondMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18}},{&quot;FirstMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&quot;SecondMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18}},{&quot;FirstMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18},&quot;SecondMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18}},{&quot;FirstMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SecondMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18}},{&quot;FirstMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SecondMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18}},{&quot;FirstMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SecondMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18}},{&quot;FirstMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:18},&quot;SecondMove&quot;:{&q....
        /// </summary>
        internal static string Scenario_XuanXuanQiJing_B25_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_XuanXuanQiJing_B25_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SecondMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:9,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&qu....
        /// </summary>
        internal static string Scenario_XuanXuanQiJing_B25_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_XuanXuanQiJing_B25_PlayerMoveExtension", resourceCulture);
            }
        }
    }
}
