//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScenarioCollection.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HashimotoUtaro_MappedJsonExtension {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HashimotoUtaro_MappedJsonExtension() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScenarioCollection.Resources.HashimotoUtaro_MappedJsonExtension", typeof(HashimotoUtaro_MappedJsonExtension).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SecondMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;ThirdMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16},&quot;FourthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:17},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:17}}]},{&quot;ThirdMove&quot;:{&quot;x&quot;:8,....
        /// </summary>
        internal static string Scenario_WindAndTime_Q29273_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WindAndTime_Q29273_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:17},&quot;SecondMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18}}]},{&quot;ThirdMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17},&quot;FourthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18}},{&quot;ThirdMove&quot;:{&quot;x&quot;:6,....
        /// </summary>
        internal static string Scenario_WindAndTime_Q29273_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WindAndTime_Q29273_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17},&quot;SecondMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16},&quot;FourthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:14},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&qu....
        /// </summary>
        internal static string Scenario_WindAndTime_Q29366_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WindAndTime_Q29366_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16},&quot;SecondMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16},&quot;FourthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:8,&qu....
        /// </summary>
        internal static string Scenario_WindAndTime_Q29958_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WindAndTime_Q29958_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:15},&quot;SecondMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&quot;FourthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:16},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:14},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:14},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:14},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&qu....
        /// </summary>
        internal static string Scenario_WindAndTime_Q29961_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WindAndTime_Q29961_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:12},&quot;SecondMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:12},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:13},&quot;FourthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:15},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:14}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:13},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:14},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:14},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:14},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&qu....
        /// </summary>
        internal static string Scenario_WindAndTime_Q30005_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WindAndTime_Q30005_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:13},&quot;SecondMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:14},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:12},&quot;FourthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:15},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:13},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:14}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:14},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:13}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:13}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:13},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:14}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:13},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:13}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:14},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:13}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&qu....
        /// </summary>
        internal static string Scenario_WindAndTime_Q30005_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WindAndTime_Q30005_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16},&quot;SecondMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:17},&quot;FourthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:15},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&qu....
        /// </summary>
        internal static string Scenario_WindAndTime_Q30034_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WindAndTime_Q30034_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:17},&quot;SecondMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:17},&quot;FourthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:16},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:9,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:10,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&q....
        /// </summary>
        internal static string Scenario_WindAndTime_Q30034_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WindAndTime_Q30034_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:16},&quot;SecondMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:16},&quot;FourthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&qu....
        /// </summary>
        internal static string Scenario_WindAndTime_Q30053_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WindAndTime_Q30053_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:15},&quot;SecondMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:14},&quot;FourthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:14},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&qu....
        /// </summary>
        internal static string Scenario_WindAndTime_Q30150_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WindAndTime_Q30150_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:11},&quot;SecondMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:12},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:12},&quot;FourthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:14},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:11},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:14}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:13},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:11}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:9},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:13}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:13},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:14}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:14},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:11}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:12},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:13}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quo....
        /// </summary>
        internal static string Scenario_WindAndTime_Q30199_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WindAndTime_Q30199_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:14},&quot;SecondMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:13},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:12},&quot;FourthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:12},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:14},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:14}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:12}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:11},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:12}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:13},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:12}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:12},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:10}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:14},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:14}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&qu....
        /// </summary>
        internal static string Scenario_WindAndTime_Q30199_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WindAndTime_Q30199_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:11},&quot;SecondMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:14},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:12},&quot;FourthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:14},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:13},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:12},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:13}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:14}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:14},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&qu....
        /// </summary>
        internal static string Scenario_WindAndTime_Q30221_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WindAndTime_Q30221_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:14},&quot;SecondMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:17},&quot;FourthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:14},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&qu....
        /// </summary>
        internal static string Scenario_WindAndTime_Q30222_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WindAndTime_Q30222_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:15},&quot;SecondMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16},&quot;FourthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:9,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:13},&quot;SixthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&qu....
        /// </summary>
        internal static string Scenario_WindAndTime_Q30222_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WindAndTime_Q30222_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:15},&quot;SecondMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:15},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:16},&quot;FourthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&qu....
        /// </summary>
        internal static string Scenario_WindAndTime_Q30225_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WindAndTime_Q30225_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:15},&quot;SecondMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:15},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:15},&quot;FourthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:15},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&qu....
        /// </summary>
        internal static string Scenario_WindAndTime_Q30225_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WindAndTime_Q30225_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:15},&quot;SecondMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:18},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&qu....
        /// </summary>
        internal static string Scenario_WindAndTime_Q30229_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WindAndTime_Q30229_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:15},&quot;SecondMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:14},&quot;FourthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&qu....
        /// </summary>
        internal static string Scenario_WindAndTime_Q30229_ChallengeMoveExtension_2 {
            get {
                return ResourceManager.GetString("Scenario_WindAndTime_Q30229_ChallengeMoveExtension_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:18},&quot;SecondMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:17},&quot;FourthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&qu....
        /// </summary>
        internal static string Scenario_WindAndTime_Q30229_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WindAndTime_Q30229_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:18},&quot;SecondMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:17},&quot;FourthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&qu....
        /// </summary>
        internal static string Scenario_WindAndTime_Q30229_PlayerMoveExtension_2 {
            get {
                return ResourceManager.GetString("Scenario_WindAndTime_Q30229_PlayerMoveExtension_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16},&quot;SecondMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;FourthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&qu....
        /// </summary>
        internal static string Scenario_WindAndTime_Q30234_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WindAndTime_Q30234_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:15},&quot;SecondMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:14},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16},&quot;FourthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&qu....
        /// </summary>
        internal static string Scenario_WindAndTime_Q30248_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WindAndTime_Q30248_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SecondMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17},&quot;FourthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:16},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:14},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&qu....
        /// </summary>
        internal static string Scenario_WindAndTime_Q30248_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WindAndTime_Q30248_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:15},&quot;SecondMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16},&quot;FourthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&qu....
        /// </summary>
        internal static string Scenario_WindAndTime_Q30269_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WindAndTime_Q30269_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SecondMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:15},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:13},&quot;FourthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:14},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&qu....
        /// </summary>
        internal static string Scenario_WindAndTime_Q30274_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WindAndTime_Q30274_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17},&quot;SecondMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16},&quot;FourthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&qu....
        /// </summary>
        internal static string Scenario_WindAndTime_Q30275_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WindAndTime_Q30275_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:15},&quot;SecondMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16},&quot;FourthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&qu....
        /// </summary>
        internal static string Scenario_WindAndTime_Q30275_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WindAndTime_Q30275_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SecondMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:16},&quot;FourthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:14},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&qu....
        /// </summary>
        internal static string Scenario_WindAndTime_Q30322_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WindAndTime_Q30322_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:14},&quot;SecondMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:16},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&qu....
        /// </summary>
        internal static string Scenario_WindAndTime_Q30322_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WindAndTime_Q30322_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17},&quot;SecondMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&quot;FourthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:15},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:15}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&qu....
        /// </summary>
        internal static string Scenario_WindAndTime_Q30358_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WindAndTime_Q30358_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:15},&quot;SecondMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:15},&quot;FourthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:15},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:8,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&qu....
        /// </summary>
        internal static string Scenario_WindAndTime_Q30358_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WindAndTime_Q30358_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&quot;SecondMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:18},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;FourthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:7,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&qu....
        /// </summary>
        internal static string Scenario_WindAndTime_Q30370_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WindAndTime_Q30370_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16},&quot;SecondMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;FourthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18}},{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:6,&qu....
        /// </summary>
        internal static string Scenario_WindAndTime_Q30403_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WindAndTime_Q30403_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;SecondMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:17},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16},&quot;FourthMove&quot;:{&quot;x&quot;:5,&quot;y&quot;:17},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:3,&quot;y&quot;:17}},{&quot;FifthMove&quot;:{&quot;x&quot;:3,&qu....
        /// </summary>
        internal static string Scenario_WindAndTime_Q30403_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WindAndTime_Q30403_PlayerMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:11},&quot;SecondMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:15},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15},&quot;FourthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:18},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:4,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:14},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:14},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&qu....
        /// </summary>
        internal static string Scenario_WindAndTime_Q30406_ChallengeMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WindAndTime_Q30406_ChallengeMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:17},&quot;SecondMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:15},&quot;SecondLevel&quot;:[{&quot;ThirdMove&quot;:{&quot;x&quot;:2,&quot;y&quot;:14},&quot;FourthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:15},&quot;ThirdLevel&quot;:[{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:14},&quot;SixthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:14}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:12}},{&quot;FifthMove&quot;:{&quot;x&quot;:0,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:12}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:12},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:14}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:16},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:12}},{&quot;FifthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:18},&quot;SixthMove&quot;:{&quot;x&quot;:1,&quot;y&quot;:12}},{&quot;FifthMove&quot;:{&quot;x&quot;:2,&qu....
        /// </summary>
        internal static string Scenario_WindAndTime_Q30406_PlayerMoveExtension {
            get {
                return ResourceManager.GetString("Scenario_WindAndTime_Q30406_PlayerMoveExtension", resourceCulture);
            }
        }
    }
}
